backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Cars"
    name: "cars"
    folder: "cars"
    create: true
    fields:
      - {label: "Model", name: "title", widget: "string"}
      - { label: "Year", name: "year", widget: "number"}